AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  student-api

  Sample SAM Template for student-api

Globals:
  Function:
    Timeout: 30
    MemorySize: 128

    LoggingConfig:
      LogFormat: JSON
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.app
      Runtime: python3.9
      Events:
        GetStudent:
          Type: Api
          Properties:
            Path: /students
            Method: get
        PutStudent:
          Type: Api
          Properties:
            Path: /students
            Method: post
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref StudentTable
  StudentTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: student-new
      AttributeDefinitions:
        - 
          AttributeName: student_id
          AttributeType: "S"
        - 
          AttributeName: student_name
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: student_id
          KeyType: HASH
        -
          AttributeName: student_name
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5